### ISSUE TITLE
Would like to contribute but no Idea on the frameworks any guidance to the relavent docs?

### ISSUE THREAD

**Issue by rahulraman-electrical** [rush86999/atomic#10]
Hi there, I really like the idea of PA scheduler, I would like to contribute to the project in the front end side of things. I have worked on web apps only with HTML, CSS, JS, NODEJs and Express. When I had a look at the NEXTjs web docs, I couldn't locate a mobile application guide only the one for web application, can you guide me to some resources to get myself started with this ? Sorry to ask this in an issue thread, I couldn't find a common medium between us to contact each other 😓

**Comment by rush86999** [comment]
Thanks for trying to support the project. So I made the web app in nextjs but have not open sourced it yet. Being solo, my time is going towards new feature development related to the upcoming Chat interface. If you can wait, I would like to open source it after I'm done with my road map. I want to possibly make it more organized around self hosted dockerized version. It would be great if you could tackle the server side that is already available into docker containers. GPT-4 can likely help you in a step by step process for this.

**Comment by rahulraman-electrical** [comment]
Oh! I was just looking for docker's documentation. I am not at all familiar with GPT or docker. I am more of a self learned front end dev so I thought that might be of some help 😄. I would be more of an hassle in your road map, I think i will wait for this to go open source and work on learning nextjs then. Thanks for the initiative :)
